services:
  - type: web
    name: card-price-checker
    runtime: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
